### ISSUE TITLE
Basemap not rendering

### ISSUE THREAD

**Issue by daniellejwarden** [gavinr/esri-leaflet-svelte-demo#2]
Current Behavior:
Clicking link redirects to example, markers rendering, basemap is not

Expected Behavior:
Expected to see basemap render in demo

Environment:
- OS: Windows
- Chrome: Version 95.0.4638.69 (Official Build) (64-bit)

**Comment by gavinr** [comment]
Thank you for logging this. I think the issue is that there is no valid API key here:
https://github.com/gavinr/esri-leaflet-svelte-demo/blob/master/src/Map.svelte#L24

If you deploy the code on your server and add an API key, it should work. 

In the longer-term, I need to figure out a good way to include a valid API key here.

**Comment by gavinr** [comment]
I added a "Getting Started" area to help with this, https://github.com/gavinr/esri-leaflet-svelte-demo#getting-started and also added the necessary [build logic](https://github.com/gavinr/esri-leaflet-svelte-demo/commit/092bf27ebb02e03fae2733642aac6ad577c1b2bf#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R18) to properly pull in the API key. Thanks again!

**Comment by daniellejwarden** [comment]
Thanks for the assist!
